### ISSUE TITLE
Export full vehicle as one single DAE file

### ISSUE THREAD

**Issue by masskro0** [BeamNG/BeamNGpy#58]
Hello,

is it possible to export a vehicle with all parts and configurations into one single DAE file? I want to add parked cars to my scenario and adding Vehicle objects decrease the performance drastically, so I want to add them as StaticObjects. I found out that JBeam files configure the cars, but since it is not possible to add them to StaticObject files, what could be done alternatively?

**Comment by Palculator** [comment]
Hey, this sounds easy in concept, but making a combined mesh that accurately replicates the exact look of a vehicle is not trivial due to all the other aspects of mashes like the materials you'd have to replicate. The material system in particular isn't as simple as putting everything related into one texture. Furthermore, we are actually slowly phasing out the DAE format, so work on that front would soon be obsolete.

In the meantime, we already do have a basic GLTF *exporter*, but the engine hasn't been switched to use those for vehicles/objects, so it's basically only one way. You could, however, export to GLTF, convert that to DAE and use that in the meantime. It would also not include any of the textures, due to the complications mentioned above. Hacky, but if it works it works. 

![blender_0kFs8DDkW9](https://user-images.githubusercontent.com/37553150/86463408-b79e3c00-bd2d-11ea-9f35-baa2d2e35ed4.png)

If a vehicle looking like this as a placeholder is good enough for your case, you can manually export a vehicle as a GLTF by adding the GLTF exporter UI app from the UI apps menu. If that works for you I can also expose that function to Python.
