### ISSUE TITLE
BNG.Research multi-threading

### ISSUE THREAD

**Issue by NismoR** [BeamNG/BeamNGpy#62]
Hello, I'm trying to separate the vehicle control from the sensor polling on separate threads. Is the BNG.Research capable of that at all? 
Here is my code what I'm trying to run:
[BNGpy Multi-Threading](https://pastebin.com/VegQmHSU)

And here are the error messages that I've got:
[BNGpy Multi-Threading Errors](https://pastebin.com/TN9KXYnx)

**Comment by alessiogambi** [comment]
Hi
I cannot access your code at the moment so I cannot comment on it. But AFAIK beamngpy assumes that only one instance is connected at the time, and instances are not thread safe. that is handling of messages/interactions with the simulator must be sequential and your code has to handle sharing access to the API.

**Comment by NismoR** [comment]
Yes, it was my fault, I've edited the comment so now the code is accessible.
I'm sad to hear that, but thank you for your quick reply.
I hope they'll change it, since the unknown delays can cause disturbances in a faster control loop.

**Comment by alessiogambi** [comment]
@NismoR: Do your control loops work in _real_-time? Otherwise, the solution is to run the simulation synchronously. You can pause the simulation, read and process all the data, send control commands back, and resume the simulation exactly from where it was paused. There should be also a sensor that gives you the "simulation time," in case you need it.

**Comment by pascale-commits** [comment]
Multi-threading is not a planned feature. Use the solution suggested by @alessiogambi for now.
